import Header from "@/components/Header";
import "./globals.css";
import clsx from "clsx";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "h-screen ")}>
        <div className="mobile-frame w-[400px] h-screen overflow-x-hidden overflow-y-auto">
          {children}
          
        </div>
      </body>
    </html>
  );
}
